"""Assets endpoint declarations."""

BOS_ASSET = "https://batteryos.com/api/v1/asset"

ENDPOINTS = [
    {"endpoint": "/{iso}/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/{asset_slug}/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/{asset_slug}/timeline/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/owners/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/qse/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/revenue/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/revenue/perfect/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/revenue/perfect/eo/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/volume/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/volume/perfect/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/volume/perfect/eo/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/volume/dl/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/volume/dispatch/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/{asset_slug}/volume/dl/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/asset/{a}/component/{c}/resource/{r}/volume/dl/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/bosindex/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/bosindex/perfect/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/availability/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/performance/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/percentiles/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/ranking/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/hsl/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/{asset_slug}/hsl/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/{iso}/cycles/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/fixtures/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/new/asset/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/new/res_name/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
    {"endpoint": "/analysis/{slug}/toggle_favorite_status/",
     "host": BOS_ASSET, "api_key": "BOS_API"},
]
