"""Calc endpoint declarations."""

BOS = "https://batteryos.com/api/v1"
TITAN = "https://batteryos.com/api/v1"

ENDPOINTS = [
    {"endpoint": "/data/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/data/{slug}/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/data/{slug}/calc/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/status/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/summary/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/nodes/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/nodes/{node_slug}/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/scenarios/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/scenarios/{scenario_slug}/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/nodescenarios/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/nodescenarios/{ns}/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/nodescenarios/{ns}/result/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/nodescenarios/{ns}/daily_result/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/nodescenarios/{ns}/params/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/calc/{slug}/nodescenarios/{ns}/status/",
     "host": BOS, "api_key": "BOS_API"},
    {"endpoint": "/dragonet/calc/",
     "host": TITAN, "api_key": "BOS_API"},
]
